### ISSUE TITLE
The project doesn't work.

### ISSUE THREAD

**Issue by Levelheader** [GraxCode/zelixkiller#4]
I tried creating an instance of this project in eclipse, using the utilities needed, aside from ASM. The only utility that was close to working was the asm-all-6.0_BETA. There are some big problems though, like MethodNode owner not being accessible as well as ConstantValue subtype errors.

**Comment by GraxCode** [comment]
I'm using a modified version of asm by lpk that I will add to this repo soon, but can you give more details on those ConstantValue errors?

**Comment by GenericException** [comment]
>modified version of asm by lpk

You ought to re-engineer your code to not depend on bad-code I wrote a few years ago. I've seen it be used a lot by people who probably are thinking exactly what I thought back then.

> _"Why does MethodNode/FieldNode not have a simple way to find their defining ClassNode?"_

Well, because that would be an anti-pattern. Its clearly supposed to be hierarchy based, IE:

* Class
    * Member
        * Sub-elements _(opcodes / etc)_

Sure having an field reference is handy but it breaks this hierarchy and enables bad design since _"its just faster this way"_. Making something extensible and easily reusable should be a top priority over getting something finished quickly. It'll only come back to haunt you and your users later.

You're making good stuff, it just pains me to see my bad practices being repeated by others.

**Comment by GraxCode** [comment]
Well, as long as it works I'm fine with it

**Comment by Levelheader** [comment]
Lol you're both great coders keep up the spirit.
